# Colors (Gruvbox Material Medium Light)

# Default colors
[colors.primary]
background = '#fbf1c7'
foreground = '#654735'

# Normal colors
[colors.normal]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'

[font]
size = 14.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window.padding]
x = 8
y = 8
