
add_newline = true

format = """
$username$hostname
$directory
$character
"""
[username]
format = "[$user]($style)"
style_user = "bold red"
style_root = "bold red"
show_always = true

[hostname]
format = "[@$hostname]($style) "
style = "bold red"
ssh_only = false
disabled = false

[battery]
format = "[B:](dimmed white) [$symbol$percentage](bold green)"
disabled = false
discharging_symbol = "-"
charging_symbol = "+"
unknown_symbol = "?"

[[battery.display]]
threshold = 100
style = "green"

[[battery.display]]
threshold = 30
style = "yellow"


[[battery.display]]
threshold = 10
style = "bold red"

[time]
format = "[T:](dimmed white) [$time]($style) "
disabled = false
style = "cyan"

[directory]
style = "purple"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"


